version: "3"
services:
  app:
    env_file:
      - env/.development.env
    container_name: e-learning
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      DB_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
